name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GCP_AUDIT_LABEL_NO_AUTH: 1

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    #- name: Build
    #  run: go build -v ./...

    - name: Test
      run: make function # go test -v ./...
